name: Integration tests build

on:
  push:
    branches:
      - main
    paths:
      - 'paas-mediation-integration-tests/**'
      - '.github/workflows/integration-tests-build.yaml'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'paas-mediation-integration-tests/**'
      - '.github/workflows/integration-tests-build.yaml'

permissions:
  contents: read
  pull-requests: write
  packages: write

concurrency:
  group: ci-intergation-tests-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build integration tests
    uses: Netcracker/qubership-core-infra/.github/workflows/generic-maven-build.yaml@v2.1.0
    with:
      pom-file: 'integration-tests/pom.xml'
      dry-run: true
      upload-artifact: 'false'
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets: inherit